import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/common/NavBar/Navbar";
import Layout from "@/components/common/Layout/Layout";
import Footer from "@/components/common/Footer/Footer";

const montesrrat = Montserrat({
  variable: '--font-monterrest',
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montesrrat.variable}  antialiased`}
      >
        <Navbar/>
        <Layout>
          {children}
        </Layout>
        <Footer/>
      </body>
    </html>
  );
}
